name: Docker Build and Push

on:
  push:
    tags:
      - 'ums-national-ems-admin-dev-v*'

jobs:
  ######## Development Environment ########
  Build-Dev:
    runs-on: ubuntu-latest
    if: startsWith(gitea.ref, 'refs/tags/ums-national-ems-admin-dev-v')
    steps:
      - name: Building
        uses: https://${{ secrets.DEVOPS_TOKEN }}:@gitea.ta3leem.dev/devops/cicd-template/templates/node_js_build@main
        with:
          app_name: 'ums-national-ems-admin'
          docker_registry_url: ${{ vars.CONTAINER_REGISTRY_URL }}
          docker_registry_path: mohesr/ums-national-ems-admin
          docker_image_tag: dev
          docker_registry_user: ${{ secrets.CONTAINER_REGISTRY_USER }}
          docker_registry_password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          env_file: ${{ vars.ENV_DEV }}
          cicd_tag: ${{ gitea.ref_name }}
  Deploy-Dev:
    needs: Build-Dev
    runs-on: ubuntu-latest
    if: startsWith(gitea.ref, 'refs/tags/ums-national-ems-admin-dev-v')
    container:
      image: 'gitea.ta3leem.dev/devops/infra-base-images/kubectl:${{ vars.KUBECTL_VERSION }}'
      credentials:
        username: ${{ secrets.CONTAINER_REGISTRY_USER }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    steps:
      - name: Deploying
        uses: https://${{ secrets.DEVOPS_TOKEN }}:@gitea.ta3leem.dev/devops/cicd-template/templates/kubernetes_deploy@main
        with:
          app_name: 'ums-national-ems-admin'
          kubeconfig: ${{ secrets.DEV_KUBECONFIG }}